# This workflow runs whenever a new issue is created
name: Issue opened

on: 
  issues:
    types: [opened]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
    # Add the new issue to a project board, if it needs triage
    # See https://github.com/marketplace/actions/create-project-card-action
    - name: Add issue to project board
      # Only add to project board if issue is flagged as "needs triage" or has no labels
      # NOTE: By default we flag new issues as "needs triage" in our issue template
      if: (contains(github.event.issue.labels.*.name, 'needs triage') || join(github.event.issue.labels.*.name) == '')
      uses: technote-space/create-project-card-action@v1
      # Note, this authentication token is created automatically
      # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        PROJECT: Backlog
        COLUMN: Triage
      # Ignore errors. It is possible the PR was created by someone who cannot be assigned
      continue-on-error: true
